# Generated by Django 3.0.8 on 2020-08-11 14:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('vsm', '0002_auto_20200811_1324'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vsmprofile',
            name='about_person',
        ),
        migrations.RemoveField(
            model_name='vsmprofile',
            name='linkedin_link',
        ),
        migrations.RemoveField(
            model_name='vsmprofile',
            name='token',
        ),
        migrations.AlterField(
            model_name='vsmprofile',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='vsm_profile', to=settings.AUTH_USER_MODEL),
        ),
    ]
