# Generated by Django 3.0.8 on 2020-08-11 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vsm', '0003_auto_20200811_1933'),
    ]

    operations = [
        migrations.CreateModel(
            name='FAQ',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('que', models.TextField()),
                ('ans', models.TextField()),
            ],
        ),
    ]
