# Generated by Django 3.0.8 on 2020-08-11 14:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vsm', '0005_instructions'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Instructions',
            new_name='Instruction',
        ),
    ]
