# Generated by Django 3.0.8 on 2020-08-11 18:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vsm', '0006_auto_20200811_1951'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='instruction',
            name='instruction',
        ),
        migrations.AddField(
            model_name='instruction',
            name='ans',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='instruction',
            name='que',
            field=models.TextField(blank=True, null=True),
        ),
    ]
