# Generated by Django 3.0.8 on 2020-08-11 18:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vsm', '0007_auto_20200812_0003'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vsmprofile',
            name='city',
        ),
        migrations.RemoveField(
            model_name='vsmprofile',
            name='country',
        ),
        migrations.RemoveField(
            model_name='vsmprofile',
            name='zip_code',
        ),
        migrations.AddField(
            model_name='vsmprofile',
            name='cash',
            field=models.DecimalField(decimal_places=10, default=1000000, max_digits=50),
        ),
        migrations.AddField(
            model_name='vsmprofile',
            name='is_iitb',
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
