# Generated by Django 3.0.8 on 2020-08-11 18:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vsm', '0008_auto_20200812_0009'),
    ]

    operations = [
        migrations.AddField(
            model_name='vsmprofile',
            name='roll_number',
            field=models.CharField(default='not_iitb', max_length=10),
        ),
    ]
