# Generated by Django 3.0.8 on 2020-08-12 02:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vsm', '0009_vsmprofile_roll_number'),
    ]

    operations = [
        migrations.RenameField(
            model_name='vsmprofile',
            old_name='college',
            new_name='city',
        ),
        migrations.AddField(
            model_name='vsmprofile',
            name='demat_accout',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='vsmprofile',
            name='hostel',
            field=models.IntegerField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='vsmprofile',
            name='program',
            field=models.TextField(blank=True, max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='vsmprofile',
            name='zip_code',
            field=models.TextField(blank=True, max_length=250, null=True),
        ),
    ]
