# Generated by Django 3.0.8 on 2020-08-12 02:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vsm', '0011_vsmprofile_college'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vsmprofile',
            name='hostel',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
