# Generated by Django 3.0.8 on 2020-08-16 02:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('vsm', '0013_auto_20200816_0816'),
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=10, unique=True)),
                ('name', models.CharField(max_length=20, unique=True)),
                ('market_cap', models.DecimalField(decimal_places=2, default=0.0, max_digits=20)),
                ('current_market_price', models.DecimalField(decimal_places=2, default=0.0, max_digits=20)),
                ('change', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('stocks_availible', models.IntegerField(default=0)),
            ],
        ),
        migrations.AlterField(
            model_name='vsmprofile',
            name='cash',
            field=models.DecimalField(decimal_places=4, default=1000000, max_digits=50),
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_type', models.CharField(blank=True, choices=[('buy', 'BUY'), ('sell', 'SELL')], max_length=20, null=True)),
                ('quantity', models.IntegerField(default=0)),
                ('bid_price', models.DecimalField(decimal_places=4, default=0, max_digits=20)),
                ('verified', models.BooleanField(default=False)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vsm.Company')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vsm.VSMProfile')),
            ],
        ),
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('show_id', models.IntegerField(default=0)),
                ('title', models.CharField(max_length=120)),
                ('content', models.TextField()),
                ('is_active', models.BooleanField(default=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('related_company', models.ManyToManyField(blank=True, to='vsm.Company')),
            ],
            options={
                'ordering': ['-timestamp', '-updated'],
            },
        ),
        migrations.CreateModel(
            name='Holding',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(default=0)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vsm.Company')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vsm.VSMProfile')),
            ],
            options={
                'unique_together': {('user', 'company')},
            },
        ),
    ]
