# Generated by Django 3.0.8 on 2020-08-16 02:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vsm', '0014_auto_20200816_0819'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='holding',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='holding',
            name='company',
        ),
        migrations.RemoveField(
            model_name='holding',
            name='user',
        ),
        migrations.RemoveField(
            model_name='news',
            name='related_company',
        ),
        migrations.RemoveField(
            model_name='transaction',
            name='company',
        ),
        migrations.RemoveField(
            model_name='transaction',
            name='user',
        ),
        migrations.DeleteModel(
            name='Company',
        ),
        migrations.DeleteModel(
            name='Holding',
        ),
        migrations.DeleteModel(
            name='News',
        ),
        migrations.DeleteModel(
            name='Transaction',
        ),
    ]
