# Generated by Django 3.0.8 on 2020-08-16 02:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vsm', '0016_auto_20200816_0824'),
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=10, unique=True)),
                ('name', models.CharField(max_length=20, unique=True)),
                ('market_cap', models.DecimalField(decimal_places=2, default=0.0, max_digits=20)),
                ('current_market_price', models.DecimalField(decimal_places=2, default=0.0, max_digits=20)),
                ('change', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('stocks_availible', models.IntegerField(default=0)),
            ],
        ),
    ]
