# Generated by Django 3.0.8 on 2020-08-16 02:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vsm', '0017_company'),
    ]

    operations = [
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('show_id', models.IntegerField(default=0)),
                ('title', models.CharField(max_length=120)),
                ('content', models.TextField()),
                ('is_active', models.BooleanField(default=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('related_company', models.ManyToManyField(blank=True, to='vsm.Company')),
            ],
            options={
                'ordering': ['-timestamp', '-updated'],
            },
        ),
    ]
