# Generated by Django 3.0.8 on 2020-08-16 03:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('vsm', '0018_news'),
    ]

    operations = [
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_type', models.CharField(blank=True, choices=[('buy', 'BUY'), ('sell', 'SELL')], max_length=20, null=True)),
                ('quantity', models.IntegerField(default=0)),
                ('bid_price', models.DecimalField(decimal_places=4, default=0, max_digits=20)),
                ('verified', models.BooleanField(default=False)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vsm.Company')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vsm.VSMProfile')),
            ],
        ),
        migrations.CreateModel(
            name='Holding',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(default=0)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vsm.Company')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vsm.VSMProfile')),
            ],
            options={
                'unique_together': {('user', 'company')},
            },
        ),
    ]
