# Generated by Django 3.0.8 on 2020-08-20 01:21

from django.db import migrations

def update_price(apps, schema_editor):
    Company = apps.get_model("vsm", "Company")
    for company in Company.objects.all():
        if company.current_market_price < 0:
            company.current_market_price = 1
        elif company.current_market_price > 100000:
             company.current_market_price = 100000
        company.stocks_availible = 2000000
        # company.market_cap = comp/any.stocks_availible * company.current_market_price
        company.save()



class Migration(migrations.Migration):

    dependencies = [
        ('vsm', '0021_companycmprecord_change'),
    ]

    operations = [
        migrations.RunPython(update_price),
    ]
