# Generated by Django 3.0.8 on 2020-08-20 01:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vsm', '0022_auto_20200820_0651'),
    ]

    operations = [
    ]
