# Generated by Django 3.0.8 on 2020-08-20 12:33

from django.db import migrations
from decimal import Decimal

def update_price(apps, schema_editor):
    Company = apps.get_model("vsm", "Company")
    json = [
        {
        "name": "Eicher Motors Ltd.(L)Add to",
        "is": "Very Good",
        "cmp": "21,989",
        "pc": "4.66%",
        "mk": "57,368",
        "h": "23,428",
        "l": "12,460"
        },
        {
        "name": "Tata Motors Ltd.(L)Add to",
        "is": "Somewhat\nGood",
        "cmp": "115.5",
        "pc": "3.68%",
        "mk": "34,411",
        "h": "201.8",
        "l": "63.6"
        },
        {
        "name": "TVS Motor Company Ltd.(M)Add to",
        "is": "Very Good",
        "cmp": "409.7",
        "pc": "2.62%",
        "mk": "18,968",
        "h": "503",
        "l": "240.1"
        },
        {
        "name": "Maruti Suzuki India Ltd.(L)Add to",
        "is": "Very Good",
        "cmp": "6,527",
        "pc": "2.61%",
        "mk": "1,92,144",
        "h": "7,755",
        "l": "4,002"
        },
        {
        "name": "Bharat Forge Ltd.(M)Add to",
        "is": "Very Good",
        "cmp": "401.1",
        "pc": "2.39%",
        "mk": "18,237",
        "h": "533.1",
        "l": "207.8"
        },
        {
        "name": "Mahindra & Mahindra Ltd.(L)Add to",
        "is": "Very Good",
        "cmp": "614.1",
        "pc": "1.93%",
        "mk": "74,909",
        "h": "624.9",
        "l": "245.8"
        },
        {
        "name": "Bajaj Finance Ltd.(L)Add to",
        "is": "Very Good",
        "cmp": "3,263",
        "pc": "0.82%",
        "mk": "1,94,994",
        "h": "4,923",
        "l": "1,783"
        },
        {
        "name": "Mahindra & Mahindra Financial Services Ltd.(M)Add to",
        "is": "Very Good",
        "cmp": "127",
        "pc": "0.79%",
        "mk": "15,574",
        "h": "245.8",
        "l": "76.47"
        },
        {
        "name": "Kotak Mahindra Bank Ltd.(L)Add to",
        "is": "Very Good",
        "cmp": "1,334",
        "pc": "0.75%",
        "mk": "2,61,992",
        "h": "1,740",
        "l": "1,000"
        },
        {
        "name": "ICICI Bank Ltd.(L)Add to",
        "is": "Very Good",
        "cmp": "352.2",
        "pc": "0.33%",
        "mk": "2,27,348",
        "h": "552.4",
        "l": "269"
        },
        {
        "name": "State Bank Of India(L)Add to",
        "is": "Very Good",
        "cmp": "192",
        "pc": "-0.08%",
        "mk": "1,71,040",
        "h": "351",
        "l": "150"
        },
        {
        "name": "ICICI Lombard General Insurance Co Ltd.(L)Add to",
        "is": "Very Good",
        "cmp": "1,348",
        "pc": "-0.12%",
        "mk": "61,347",
        "h": "1,440",
        "l": "806"
        },
        {
        "name": "Housing Development Finance Corporation Ltd.(L)Add to",
        "is": "Very Good",
        "cmp": "1,777",
        "pc": "-0.13%",
        "mk": "3,08,639",
        "h": "2,500",
        "l": "1,473"
        },
        {
        "name": "HDFC Bank Ltd.(L)Add to",
        "is": "Very Good",
        "cmp": "1,028",
        "pc": "-1.30%",
        "mk": "5,72,690",
        "h": "1,304",
        "l": "738.9"
        },
        {
        "name": "Axis Bank Ltd.(L)Add to",
        "is": "Very Good",
        "cmp": "434.9",
        "pc": "1.39%",
        "mk": "1,21,037",
        "h": "765.9",
        "l": "285"
        },
        {
        "name": "Britannia Industries Ltd.(L)Add to",
        "is": "Very Good",
        "cmp": "3,852",
        "pc": "0.94%",
        "mk": "91,879",
        "h": "4,015",
        "l": "2,101"
        },
        {
        "name": "Colgate-Palmolive (India) Ltd.(L)Add to",
        "is": "Very Good",
        "cmp": "1,443",
        "pc": "0.32%",
        "mk": "39,132",
        "h": "1,641",
        "l": "1,065"
        },
        {
        "name": "Procter & Gamble Hygiene & Health Care Ltd.(L)Add to",
        "is": "Very Good",
        "cmp": "10,296",
        "pc": "-0.06%",
        "mk": "33,443",
        "h": "12,700",
        "l": "8,500"
        },
        {
        "name": "Hindustan Unilever Ltd.(L)Add to",
        "is": "Very Good",
        "cmp": "2,194",
        "pc": "-0.15%",
        "mk": "5,16,396",
        "h": "2,614",
        "l": "1,708"
        },
        {
        "name": "ITC Ltd.(L)Add to",
        "is": "Very Good",
        "cmp": "192.8",
        "pc": "-0.44%",
        "mk": "2,38,169",
        "h": "266.2",
        "l": "134.9"
        },
        {
        "name": "Tata Consumer Products Ltd.(L)Add to",
        "is": "Somewhat\nGood",
        "cmp": "447.7",
        "pc": "-0.46%",
        "mk": "41,447",
        "h": "452.3",
        "l": "214"
        },
        {
        "name": "Nestle India Ltd.(L)Add to",
        "is": "Very Good",
        "cmp": "16,496",
        "pc": "-0.52%",
        "mk": "1,59,883",
        "h": "18,301",
        "l": "11,545"
        },
        {
        "name": "Marico Ltd.(L)Add to",
        "is": "Very Good",
        "cmp": "363.2",
        "pc": "-1.25%",
        "mk": "47,486",
        "h": "403.7",
        "l": "233.8"
        },
        {
        "name": "Godrej Consumer Products Ltd.(L)Add to",
        "is": "Very Good",
        "cmp": "677.2",
        "pc": "-2.17%",
        "mk": "70,781",
        "h": "771.8",
        "l": "425.1"
        },
        {
        "name": "Adani Ports and Special Economic Zone Ltd.(L)Add to",
        "is": "Somewhat\nGood",
        "cmp": "327",
        "pc": "3.83%",
        "mk": "63,990",
        "h": "428.9",
        "l": "203.4"
        },
        {
        "name": "Shree Cement Ltd.(L)Add to",
        "is": "Very Good",
        "cmp": "22,097",
        "pc": "2.32%",
        "mk": "77,917",
        "h": "25,341",
        "l": "15,500"
        },
        {
        "name": "Bharti Airtel Ltd.(L)Add to",
        "is": "Somewhat\nGood",
        "cmp": "558.9",
        "pc": "1.83%",
        "mk": "2,99,401",
        "h": "611.7",
        "l": "325.6"
        },
        {
        "name": "Grasim Industries Ltd.(L)Add to",
        "is": "Very Good",
        "cmp": "633.9",
        "pc": "1.48%",
        "mk": "41,087",
        "h": "836.5",
        "l": "380"
        },
        {
        "name": "Indraprastha Gas Ltd.(L)Add to",
        "is": "Very Good",
        "cmp": "393.9",
        "pc": "1.43%",
        "mk": "27,185",
        "h": "534.4",
        "l": "284.6"
        },
        {
        "name": "Apollo Hospitals Enterprise Ltd.(L)Add to",
        "is": "Very Good",
        "cmp": "1,676",
        "pc": "1.31%",
        "mk": "23,014",
        "h": "1,814",
        "l": "1,047"
        },
        {
        "name": "Ultratech Cement Ltd.(L)Add to",
        "is": "Very Good",
        "cmp": "4,042",
        "pc": "0.97%",
        "mk": "1,15,547",
        "h": "4,753",
        "l": "2,913"
        },
        {
        "name": "Mindtree Ltd.(M)Add to",
        "is": "Very Good",
        "cmp": "1,141",
        "pc": "1.29%",
        "mk": "18,530",
        "h": "1,144",
        "l": "667.3"
        },
        {
        "name": "Tata Consultancy Services Ltd.(L)Add to",
        "is": "Very Good",
        "cmp": "2,259",
        "pc": "0.43%",
        "mk": "8,43,968",
        "h": "2,357",
        "l": "1,504"
        },
        {
        "name": "Infosys Ltd.(L)Add to",
        "is": "Very Good",
        "cmp": "944.6",
        "pc": "-0.58%",
        "mk": "4,04,676",
        "h": "986",
        "l": "511.1"
        },
        {
        "name": "Info Edge (India) Ltd.(L)Add to",
        "is": "Very Good",
        "cmp": "3,354",
        "pc": "4.82%",
        "mk": "39,206",
        "h": "3,310",
        "l": "1,580"
        },
        {
        "name": "Wipro Ltd.(L)Add to",
        "is": "Very Good",
        "cmp": "278.1",
        "pc": "-1.05%",
        "mk": "1,60,634",
        "h": "290.6",
        "l": "159.6"
        },
        {
        "name": "Hindalco Industries Ltd.(L)Add to",
        "is": "Not Good",
        "cmp": "175.8",
        "pc": "8.32%",
        "mk": "36,468",
        "h": "221.2",
        "l": "85.05"
        },
        {
        "name": "Steel Authority Of India Ltd.(M)Add to",
        "is": "Somewhat\nGood",
        "cmp": "36.75",
        "pc": "6.37%",
        "mk": "14,271",
        "h": "51.85",
        "l": "20.15"
        },
        {
        "name": "Tata Steel Ltd.(L)Add to",
        "is": "Somewhat\nGood",
        "cmp": "395.8",
        "pc": "6.33%",
        "mk": "44,823",
        "h": "505.9",
        "l": "250.9"
        },
        {
        "name": "Hindustan Zinc Ltd.(L)Add to",
        "is": "Very Good",
        "cmp": "218.3",
        "pc": "5.89%",
        "mk": "87,105",
        "h": "225",
        "l": "122"
        },
        {
        "name": "Cipla Ltd.(L)Add to",
        "is": "Very Good",
        "cmp": "722.5",
        "pc": "1.22%",
        "mk": "57,558",
        "h": "734",
        "l": "356.8"
        },
        {
        "name": "Torrent Pharmaceuticals Ltd.(L)Add to",
        "is": "Very Good",
        "cmp": "2,860",
        "pc": "1.12%",
        "mk": "47,867",
        "h": "2,845",
        "l": "1,555"
        },
        {
        "name": "Dr. Reddys Laboratories Ltd.(L)Add to",
        "is": "Very Good",
        "cmp": "4,605",
        "pc": "-0.64%",
        "mk": "77,038",
        "h": "4,667",
        "l": "2,352"
        },
        {
        "name": "Lupin Ltd.(L)Add to",
        "is": "Very Good",
        "cmp": "928",
        "pc": "-1.34%",
        "mk": "42,625",
        "h": "955.9",
        "l": "505"
        },
        {
        "name": "Union Bank Of India(M)Add to",
        "is": "Not Good",
        "cmp": "29.35",
        "pc": "0.86%",
        "mk": "18,644",
        "h": "66.75",
        "l": "22.6"
        },
        {
        "name": "State Bank Of India(L)Add to",
        "is": "Very Good",
        "cmp": "191.5",
        "pc": "-0.08%",
        "mk": "1,71,040",
        "h": "351",
        "l": "149.6"
        },
        {
        "name": "Jubilant FoodWorks Ltd.(L)Add to",
        "is": "Very Good",
        "cmp": "1,864",
        "pc": "3.12%",
        "mk": "23,853",
        "h": "1,973",
        "l": "1,078"
        },
        {
        "name": "Havells India Ltd.(L)Add to",
        "is": "Very Good",
        "cmp": "605.7",
        "pc": "2.92%",
        "mk": "36,841",
        "h": "765.1",
        "l": "447.2"
        },
        {
        "name": "Titan Company Ltd.(L)Add to",
        "is": "Very Good",
        "cmp": "1,106",
        "pc": "2.85%",
        "mk": "95,428",
        "h": "1,390",
        "l": "720"
        },
        {
        "name": "Asian Paints Ltd.(L)Add to",
        "is": "Very Good",
        "cmp": "1,717",
        "pc": "0.17%",
        "mk": "1,64,435",
        "h": "1,916",
        "l": "1,432"
        },
        {
        "name": "NMDC Ltd.(L)Add to",
        "is": "Somewhat\nGood",
        "cmp": "86.6",
        "pc": "2.00%",
        "mk": "25,995",
        "h": "139.5",
        "l": "62"
        },
        {
        "name": "Oil & Natural Gas Corporation Ltd.(L)Add to",
        "is": "Very Good",
        "cmp": "76.95",
        "pc": "0.98%",
        "mk": "95,862",
        "h": "149.7",
        "l": "51.8"
        },
        {
        "name": "NTPC Ltd.(L)Add to",
        "is": "Somewhat\nGood",
        "cmp": "85.9",
        "pc": "0.23%",
        "mk": "84,796",
        "h": "129.6",
        "l": "74"
        },
        {
        "name": "NBCC (India) Ltd.(S)Add to",
        "is": "Somewhat\nGood",
        "cmp": "23.1",
        "pc": "0.22%",
        "mk": "4,149",
        "h": "45",
        "l": "14.1"
        },
        {
        "name": "Zee Entertainment Enterprises Ltd.(M)Add to",
        "is": "Very Good",
        "cmp": "145.5",
        "pc": "1.50%",
        "mk": "13,769",
        "h": "376.2",
        "l": "114"
        },
        {
        "name": "TV18 Broadcast Ltd.(M)Add to",
        "is": "Not Good",
        "cmp": "34.2",
        "pc": "-4.60%",
        "mk": "6,146",
        "h": "41.7",
        "l": "11.85"
        },
        {
        "name": "Hathway Cable & Datacom Ltd.(M)Add to",
        "is": "Somewhat\nGood",
        "cmp": "39.75",
        "pc": "4.88%",
        "mk": "6,709",
        "h": "57.45",
        "l": "10.7"
        },
        {
        "name": "PVR Ltd.(M)Add to",
        "is": "Somewhat\nGood",
        "cmp": "1,139",
        "pc": "4.05%",
        "mk": "6,041",
        "h": "2,083",
        "l": "706.5"
        },
        {
        "name": "Bata India Ltd.(M)Add to",
        "is": "Very Good",
        "cmp": "1,319",
        "pc": "4.65%",
        "mk": "16,198",
        "h": "1,897",
        "l": "1,017"
        },
        {
        "name": "Siemens Ltd.(L)Add to",
        "is": "Very Good",
        "cmp": "1,169",
        "pc": "-0.14%",
        "mk": "41,686",
        "h": "1,717",
        "l": "947"
        },
        {
        "name": "Kansai Nerolac Paints Ltd.(L)Add to",
        "is": "Very Good",
        "cmp": "442.5",
        "pc": "2.34%",
        "mk": "23,303",
        "h": "573",
        "l": "296.3"
        },
        {
        "name": "Abbott India Ltd.(L)Add to",
        "is": "Very Good",
        "cmp": "16,251",
        "pc": "-0.75%",
        "mk": "34,792",
        "h": "18,569",
        "l": "8,336"
        },
        {
        "name": "Ashok Leyland Ltd.(M)Add to",
        "is": "Somewhat\nGood",
        "cmp": "48.95",
        "pc": "-1.21%",
        "mk": "14,546",
        "h": "87.5",
        "l": "33.7"
        },
        {
        "name": "RBL Bank Ltd.(M)Add to",
        "is": "Somewhat\nGood",
        "cmp": "175",
        "pc": "3.67%",
        "mk": "8,588",
        "h": "413.6",
        "l": "101.6"
        },
        {
        "name": "Bandhan Bank Ltd.(L)Add to",
        "is": "Very Good",
        "cmp": "311.1",
        "pc": "1.37%",
        "mk": "49,420",
        "h": "650",
        "l": "152.3"
        },
        {
        "name": "IndusInd Bank Ltd.(L)Add to",
        "is": "Very Good",
        "cmp": "492.9",
        "pc": "0.05%",
        "mk": "34,165",
        "h": "1,596",
        "l": "235.6"
        },
        {
        "name": "Bharat Heavy Electricals Ltd.(M)Add to",
        "is": "Not Good",
        "cmp": "36.7",
        "pc": "0.14%",
        "mk": "12,762",
        "h": "61.3",
        "l": "19.2"
        },
        {
        "name": "Oil India Ltd.(M)Add to",
        "is": "Not Good",
        "cmp": "94.05",
        "pc": "-0.32%",
        "mk": "10,231",
        "h": "174.8",
        "l": "66"
        },
        {
        "name": "Coal India Ltd.(L)Add to",
        "is": "Very Good",
        "cmp": "128.5",
        "pc": "-0.16%",
        "mk": "79,314",
        "h": "217.9",
        "l": "119.2"
        },
        {
        "name": "Phoenix Mills Ltd.(M)Add to",
        "is": "Somewhat\nGood",
        "cmp": "606.4",
        "pc": "1.76%",
        "mk": "9,144",
        "h": "979.5",
        "l": "466.2"
        },
        {
        "name": "Oberoi Realty Ltd.(M)Add to",
        "is": "Somewhat\nGood",
        "cmp": "355.4",
        "pc": "0.81%",
        "mk": "12,821",
        "h": "583.5",
        "l": "290.1"
        },
        {
        "name": "Sunteck Realty Ltd.(S)Add to",
        "is": "Not Good",
        "cmp": "224.7",
        "pc": "17.96%",
        "mk": "2,788",
        "h": "487.4",
        "l": "145"
        },
        {
        "name": "Indiabulls Real Estate Ltd.(S)Add to",
        "is": "Not Good",
        "cmp": "55.7",
        "pc": "0.45%",
        "mk": "2,521",
        "h": "113",
        "l": "36.85"
        },
        {
        "name": "DLF Ltd.(L)Add to",
        "is": "Not Good",
        "cmp": "142.4",
        "pc": "-0.07%",
        "mk": "35,273",
        "h": "266.6",
        "l": "114.5"
        }
        ]
    for company in Company.objects.all():
        company.stocks_availible = 500000

        for obj in json:
            if company.name.lower() in obj['name'].lower():
                company.current_market_price = Decimal(obj['cmp'].replace(',', ''))

        if company.current_market_price <0:
            company.current_market_price = 1
        
        company.save()




class Migration(migrations.Migration):

    dependencies = [
        ('vsm', '0023_auto_20200820_0656'),
    ]

    operations = [
        migrations.RunPython(update_price),
    ]
