# Generated by Django 3.0.8 on 2020-08-25 13:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vsm', '0025_cashrecord'),
    ]

    operations = [
    ]
